version: '1.0.{build}'

assembly_info:
  patch: true
  file: MyLibrary\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  
before_build:
  nuget restore
  
build:
  project: MySolution.sln
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: ebBPnwwFR+v+p9FlTHpVoyZWqPFkz/hQsFN4BAKqiwDnWO9z7HNNpXzn95n2d3ZJ

artifacts:
- path: '**\bin\Debug\*'
  name: Files

after_test:
  ps: |
    mkdir -Path coverage-results
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:.\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe "-targetargs:.\MyLibrary.Tests\bin\Release\MyLibrary.Tests.dll -noshadow" "-filter:+[MyLibrary*]* -[*Tests]*" -skipautoprops -output:.\coverage-results\results.xml
    .\packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover --input .\coverage-results\results.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
