version: '1.0.{build}'

assembly_info:
  patch: true
  file: MyLibrary\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

environment:
  COVERALLS_REPO_TOKEN:
    secure: ebBPnwwFR+v+p9FlTHpVoyZWqPFkz/hQsFN4BAKqiwDnWO9z7HNNpXzn95n2d3ZJ

artifacts:
- path: '**\bin\Debug\*'
  name: Files
